# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_photography'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
