# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_photography_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laster_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=450)),
                ('image', models.FileField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
