# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_laster_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laster_Post',
            new_name='LasterPost',
        ),
    ]
