# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170828_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasterpost',
            name='active',
        ),
        migrations.RemoveField(
            model_name='lasterpost',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='lasterpost',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='lasterpost',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
