# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tinmoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinmoi',
            name='description',
        ),
    ]
