# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_tinmoi_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LasterPost',
            new_name='Tinnoibat',
        ),
    ]
