# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170829_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinnoibat',
            name='summary',
        ),
    ]
