# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170901_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnoibat',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
