# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_menu_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('TenLT', models.CharField(max_length=250)),
                ('TenLT_KhongDau', models.CharField(max_length=500)),
                ('ThuTu', models.IntegerField(max_length=10)),
                ('An_Hien', models.IntegerField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theloai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('TenTL', models.CharField(max_length=50)),
                ('TenTL_khongdau', models.CharField(max_length=50)),
                ('ThuTu', models.IntegerField(max_length=10)),
                ('An_Hien', models.IntegerField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('TieuDe', models.CharField(max_length=250)),
                ('TieuDe_KhongDau', models.CharField(max_length=250)),
                ('TomTat', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='images/')),
                ('Content', models.CharField(max_length=700)),
                ('SoLanXem', models.IntegerField(max_length=10000)),
                ('TinNoiBat', models.CharField(max_length=250)),
                ('An_Hien', models.IntegerField(max_length=10)),
                ('idLT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.LoaiTin')),
                ('idTL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Theloai')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='slider',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='tinmoi',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='tinnoibat',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='Tinmoi',
        ),
        migrations.DeleteModel(
            name='Tinnoibat',
        ),
        migrations.AddField(
            model_name='loaitin',
            name='idTL',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Theloai'),
        ),
    ]
