# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20170901_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaitin',
            name='idTL',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='idLT',
        ),
        migrations.AlterField(
            model_name='tin',
            name='Content',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='tin',
            name='SoLanXem',
            field=models.IntegerField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='tin',
            name='TinNoiBat',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='LoaiTin',
        ),
    ]
