# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170901_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theloai',
            name='An_Hien',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='An_Hien',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='SoLanXem',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='TinNoiBat',
        ),
    ]
