# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170901_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theloai',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='active',
        ),
    ]
