# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170904_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loaitin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Ten', models.CharField(max_length=250)),
                ('idTL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Theloai')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
