# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_loaitin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaitin',
            name='idTL',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='idTL',
        ),
        migrations.DeleteModel(
            name='Loaitin',
        ),
        migrations.DeleteModel(
            name='Theloai',
        ),
        migrations.DeleteModel(
            name='Tin',
        ),
    ]
