# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0021_auto_20170904_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=200)),
                ('Ten_KhongDau', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_TL', models.CharField(max_length=255)),
                ('Ten_TL_KhongDau', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tieu_De', models.CharField(max_length=255)),
                ('Tieu_De_KhongDau', models.CharField(max_length=255)),
                ('Tom_Tat', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('Content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='loaitin',
            name='idTL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TheLoai'),
        ),
    ]
