# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170904_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tin',
            name='Create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tin',
            name='Update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tin',
            name='idLT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.LoaiTin'),
        ),
        migrations.AddField(
            model_name='tin',
            name='idTL',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.TheLoai'),
        ),
    ]
