# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170904_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tin',
            old_name='Create_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='Update_date',
        ),
    ]
