# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_auto_20170912_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Is_Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Is_Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=255)),
                ('Is_Allowlink', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Is_Display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=255)),
                ('Decriptions', models.TextField(max_length=max)),
                ('Image', models.FileField(upload_to='images')),
                ('Is_HightLight', models.BooleanField(default=True)),
                ('Id_DanhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DanhMuc')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTHagTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Status', models.BooleanField(default=True)),
                ('Id_HashTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HashTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='loaitin',
            name='idTL',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='idLT',
        ),
        migrations.RemoveField(
            model_name='tin',
            name='idTL',
        ),
        migrations.DeleteModel(
            name='LoaiTin',
        ),
        migrations.DeleteModel(
            name='TheLoai',
        ),
        migrations.DeleteModel(
            name='Tin',
        ),
    ]
