# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170912_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.RemoveField(
            model_name='tthagtag',
            name='Id_HashTag',
        ),
        migrations.RemoveField(
            model_name='tintuc',
            name='creator',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
        migrations.DeleteModel(
            name='TTHagTag',
        ),
    ]
