# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20170912_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tintuc',
            name='Id_DanhMuc',
        ),
        migrations.DeleteModel(
            name='TinTuc',
        ),
    ]
