# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20170912_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=255)),
                ('Decriptions', models.TextField(max_length=max)),
                ('Image', models.FileField(upload_to='images')),
                ('Is_HightLight', models.BooleanField(default=True)),
                ('Id_DanhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DanhMuc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
