# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_tintuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tintuc',
            name='Decriptions',
        ),
        migrations.RemoveField(
            model_name='tintuc',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='tintuc',
            name='Is_HightLight',
        ),
    ]
