# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20170912_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Is_Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=255)),
                ('Is_Allowlink', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Is_Display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TTHagTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Status', models.BooleanField(default=True)),
                ('Id_HashTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HashTag')),
            ],
        ),
        migrations.AddField(
            model_name='tintuc',
            name='Views',
            field=models.BooleanField(default=True),
        ),
    ]
