# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 16:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_catelogy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='Content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Noi dung'),
        ),
    ]
