# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20170914_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, null=True)),
                ('idDanhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DanhMuc')),
            ],
        ),
        migrations.AddField(
            model_name='tintuc',
            name='Id_LoaiTin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.LoaiTin'),
        ),
    ]
