# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20170916_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
