# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='alt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
