# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_tintuc_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhmuc',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
