# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_danhmuc_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='Catelogy',
        ),
        migrations.RemoveField(
            model_name='danhmuc',
            name='slug',
        ),
    ]
