# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20170922_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AlterField(
            model_name='tintuc',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
